version: 1
formatters:
  simple:
    format: "%(asctime)s %(level)s:%(name)s:%(module)s:%(funcName)s:%(lineno)i:  %(message)s" 
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  etl_alert:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
