version: 1
formatters:
  simple:
    format: "%(asctime)s [%(levelname)s]: [%(name)s:%(module)s:%(funcName)s]: %(lineno)i: %(message)s" 
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: debug.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

loggers:
  etl_alert:
    level: DEBUG
    handlers: [console, debug_file]
    propagate: no
  root:
    level: DEBUG
    handlers: [console, debug_file]
